// Code generated by "stringer -type Event ./vstate/event.go"; DO NOT EDIT.

package vstate

import "strconv"

const _Event_name = "ClaimDisClaimHunterNineThirtyPmLessThen20SetStateDeleteHours48"

var _Event_index = [...]uint8{0, 5, 13, 19, 31, 41, 49, 55, 62}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
