// Code generated by "stringer -type State ./vstate/state.go"; DO NOT EDIT.

package vstate

import "strconv"

const _State_name = "ReadyBattery_lowBountyRidingCollectedDroppedService_modeTerminatedUnknownNothing"

var _State_index = [...]uint8{0, 5, 16, 22, 28, 37, 44, 56, 66, 73, 80}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
