// Code generated by "stringer -type URoles ./vstate/auth.go"; DO NOT EDIT.

package vstate

import "strconv"

const _URoles_name = "NoAuthEndUserHuntersAdminsSystem"

var _URoles_index = [...]uint8{0, 6, 13, 20, 26, 32}

func (i URoles) String() string {
	if i < 0 || i >= URoles(len(_URoles_index)-1) {
		return "URoles(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _URoles_name[_URoles_index[i]:_URoles_index[i+1]]
}
